### PR TITLE
Change to use 3 valued bool for LocalDiskFlag

### PR DESCRIPTION
**Pull request by mattcui**
For addressing [Tracker 126049889](https://www.pivotaltracker.com/story/show/126049889), basically, we want to set true to LocalDiskFlag if it's not specified in the deployment manifest.

### CODE REVIEW

**Comment by mattcui** [comment]
@maximilien It's ready for review. Thanks.

**Comment by mattcui** [comment]
@maximilien Looks like it's overkill for the new feature of opening a tracker automatically.

**Comment by maximilien** [comment]
See my comment in the softlayer-go project PR

**Comment by mattcui** [comment]
As per our discussion, I will have a try with "String" type for LocalDiskFlag. Closing this PR, I will open a new one.

**Pull request closed without merging**
