### PR TITLE
Delete bosh-init-usage.md and sl-bosh.yml

### PR DESCRIPTION
**Pull request by petergtz**
This is documented on https://bosh.io/docs/init-softlayer.html.

Having this documentation duplicated leads to stale versions on either side.

We compared https://bosh.io/docs/init-softlayer.html and this file, and we put the diff into [docs-bosh/#274](https://github.com/cloudfoundry/docs-bosh/pull/274).

Please merge this PR _after_ https://github.com/cloudfoundry/docs-bosh/pull/274 was merged.

/cc @suhlig

### CODE REVIEW

**Comment by maximilien** [comment]
@petergtz thanks for the contribution. I'll wait for cloudfoundry/docs-bosh#274

Also, in the mean time as we wait, would it make sense to add a link from the docs here to  https://bosh.io/docs/init-softlayer.html?

**Comment by petergtz** [comment]
@maximilien Ideally yes, but my hope is that cloudfoundry/docs-bosh#274 will be merged soon enough. I'll ping @cppforlife to see if there's anything blocking that PR.

**Comment by petergtz** [comment]
@maximilien cloudfoundry/docs-bosh#274 is merged now.

**Comment by maximilien** [comment]
Thanks @petergtz

**Pull request merged**
