### PR TITLE
Do not allow 64 character long names

### PR DESCRIPTION
**Pull request by vvraskin**
Hello, 

this PR addresses the issue #129. When the VM name is equal to 64 characters, the deployment is failing due to ssh problem (agent could not copy files to the VSI).

When the name with 64 characters was identified, a padding "-1" is appended to it. 
I have removed the previous workaround for > 63 characters, since longer names are accepted. 

@mattcui @maximilien Could you please have a look at this PR?

### CODE REVIEW

**Comment by mattcui** [comment]
Had a talk with @vvraskin, we all agree that it's a problem in Softlayer, we need to ask SL to fix it, but based on the experiences working with SL, it would need a pretty longer cycle, so in the meantime, we could work around it in CPI. I took a look at the code change, I don't see a UT to verify there appends "-1" when length of hostname is 64 characters.

/cc @maximilien

**Comment by maximilien** [comment]
I can buy that. Please include this in the docs.

/cc @gu-bin

**Comment by gu-bin** [comment]
I will include this in doc after the PR is merged.

**Comment by maximilien** [comment]
Thanks @gu-bin. 

@vvraskin this is still failing with conflicts. Please update and I will review.

Best,

Max

**Comment by vvraskin** [comment]
@maximilien I've resolved the conflicts, please review. 

@mattcui I didn't create a new UT, I adapted the existing one instead, vm name is exactly 64 characters if I set the prefix to this length:
https://github.com/vvraskin/bosh-softlayer-cpi/blob/master/src/bosh-softlayer-cpi/action/create_vm_test.go#L70
And I'm checking that the VM name is not equal to 64 at the end:
https://github.com/vvraskin/bosh-softlayer-cpi/blob/master/src/bosh-softlayer-cpi/action/create_vm_test.go#L82

Let me know if you want me to implement a new test for that.

**Comment by maximilien** [comment]
@vvraskin I think this is wrong. You need to rebase on @zhanggbj last PR that changed the structure.

Ideally, your PR should only include the changes you want to make. I am closing this.

Please reopen with only the changes for your PR. Thanks.

**Pull request closed without merging**
