### PR TITLE
Proposal: Use 'portable' IPs to enable manual networking with the SL CPI

### PR DESCRIPTION
**Pull request by sykesm**
This code allows a user to assign an IP to a bosh job from a subnet that is associated with the public or private vlan for the VM.  This is not code I expect to have merged - this is an approach I'd like to discuss to see if something like it makes sense. 

Why? Two reasons:
- The spiff templates in cf-release make heavy use of static IPs. These IPs are then propagated to deployed jobs via properties to other jobs in the release. For example, three etcd workers are deployed via cf-release and their IP addresses are populated into a list called `etcd-machines` that all etcd clients use to build their client configurations. There's no way to use or simulate them in the CPI today.
- When a SL VM needs to be recreated, the IP address can be lost so once a VM has been allocated and its address propagated, teams begin to avoid operations that recreate a VM.

Without other changes, we still can't deploy cf-release to SL with the existing templates in cf-release. 

We've also found that there are bugs in spiff when dealing with multiple networks and there appear to be some odd differences in how bosh sends the network spec to an agent between the director flow and the micro-bosh flows. (In particular, `manual` networks have their `type` attribute omitted when provided to the cpi's `create_vm` operation.) These all contribute to issues with deploying a pristine `cf-release`.

Note: This code makes use of go 1.6 template features but the cpi release is still using go 1.5. You should consider upgrading.

### CODE REVIEW

**Comment by cppforlife** [comment]
also why are we rewriting interfaces file?

**Comment by sykesm** [comment]
@cppforlife: because you don't have support in the agent to do what's needed. You don't support aliases and I didn't see any support for custom routes.

**Comment by maximilien** [comment]
Tracker chore [121895629](https://www.pivotaltracker.com/story/show/121895629) to investigate this proposal

**Comment by jianqiu** [comment]
@syekesm, 
Thanks for your good explanation and insights to SL portable ip, CPI, cf deployment etc.
We will get to work on it, so could you please send me a copy of your cf deployment manifest which you want to deploy to SL? Thanks!

**Comment by sykesm** [comment]
@jianqiu - I'm trying to deploy cf-release. The templates for the release and various infrastructures are there. You'll need to generate a manifest from that information as that's all an open source user gets.

This is the infrastructure template I was playing with. You can use it as a starting point if you wish:

```yaml
meta:
  environment: ~

  stemcell: (( merge || .meta.default_stemcell ))

  default_stemcell:
    # https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/light-bosh-stemcell-3215-softlayer-esxi-ubuntu-trusty-go_agent.tgz
    name: light-bosh-stemcell-3215-softlayer-esxi-ubuntu-trusty-go_agent
    version: latest

  resource_pools: (( merge ))

networks: (( merge ))

properties:
  <<: (( merge ))
  logger_endpoint:
    port: 4443

  cc: (( merge ))

  uaa:
    clients: (( merge ))

  dea_next:
    deny_networks: (( merge || nil ))
    allow_networks: (( merge || nil ))

  ccdb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: ccdb
      tag: cc
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: (( merge ))
      tag: admin

  uaadb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: (( merge ))
      tag: admin

  databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( merge ))
      - tag: admin
        name: uaaadmin
        password: (( merge ))
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
    collect_statement_statistics: null
    additional_config: (( merge || nil ))

compilation:
  workers: 3
  network: cf1-dynamic
  reuse_compilation_vms: true
  cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties ))

resource_pools:
  - name: small_z1
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: small_z2
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: medium_z1
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties ))

  - name: medium_z2
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties ))

  - name: large_z1
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties  ))

  - name: large_z2
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties  ))

  - name: runner_z1
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties  ))

  - name: runner_z2
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties  ))

  - name: router_z1
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties  ))

  - name: router_z2
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties  ))

# This is a simple config without redundancy.
jobs:
  - name: nats_z1
    instances: 1
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(2) ))
      default: [dns, gateway]

  - name: nfs_z1
    instances: 0
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(3) ))
      default: [dns, gateway]

  - name: blobstore_z1
    instances: 1
    networks:
    - name: cf1-dynamic

  - name: postgres_z1
    instances: 1
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(4) ))
      default: [dns, gateway]

  - name: router_z1
    instances: 1
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(5) ))
      default: [dns, gateway]

  - name: loggregator_z1
    instances: 0
    networks:
    - name: cf1-dynamic

  - name: doppler_z1
    instances: 1
    networks:
    - name: cf1-dynamic

  - name: loggregator_trafficcontroller_z1
    instances: 1
    networks:
    - name: cf1-dynamic

  - name: etcd_z1
    instances: 1
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(8, 9, 10) ))
      default: [dns, gateway]

  - name: consul_z1
    instances: 1
    networks:
    - name: cf1-dynamic
    - name: cf1
      static_ips: (( static_ips(12, 13, 14) ))
      default: [dns, gateway]

  - name: nats_z2
    instances: 0
    networks:
    - name: cf2-dynamic
    - name: cf2
      static_ips: (( static_ips(2) ))
      default: [dns, gateway]

  - name: router_z2
    instances: 0
    networks:
    - name: cf2-dynamic
    - name: cf2
      static_ips: (( static_ips(5) ))
      default: [dns, gateway]

  - name: etcd_z2
    instances: 0
    networks:
    - name: cf2-dynamic
    - name: cf2
      static_ips: (( static_ips(8, 9, 10) ))
      default: [dns, gateway]

  - name: consul_z2
    instances: 0
    networks:
    - name: cf2-dynamic
    - name: cf2
      static_ips: (( static_ips(12, 13, 14) ))
      default: [dns, gateway]

  - name: loggregator_z2
    instances: 0
    networks:
     - name: cf2-dynamic

  - name: doppler_z2
    instances: 0
    networks:
    - name: cf2-dynamic

  - name: loggregator_trafficcontroller_z2
    instances: 0
    networks:
    - name: cf2-dynamic

  - name: uaa_z2
    instances: 0

  - name: api_z2
    instances: 0

  - name: api_worker_z2
    instances: 0

  - name: hm9000_z2
    instances: 0

  - name: runner_z2
    instances: 0
```

This is the part of the stub that I used with the multiple networks:
```yaml
---
director_uuid: 9489a253-16f8-4dd4-b2d0-d7ac38a646b7

meta:
  environment: cf-furnace

  resource_pools:
    small:
      cloud_properties:
        Bosh_ip: 10.155.248.130
        Domain: softlayer.com
        VmNamePrefix: bosh-furnace
        EphemeralDiskSize: 20
        StartCpus: 2
        MaxMemory: 2048
        NetworkComponents:
        - MaxSpeed: 1000
        Datacenter:
          Name: dal09
        HourlyBillingFlag: true
        PrivateNetworkOnlyFlag: true
        PrimaryBackendNetworkComponent:
          NetworkVlan:
              Id: 1113235
    medium:
      cloud_properties:
        Bosh_ip: 10.155.248.130
        Domain: softlayer.com
        VmNamePrefix: bosh-furnace
        EphemeralDiskSize: 20
        StartCpus: 4
        MaxMemory: 4096
        NetworkComponents:
        - MaxSpeed: 1000
        Datacenter:
          Name: dal09
        HourlyBillingFlag: true
        PrivateNetworkOnlyFlag: true
        PrimaryBackendNetworkComponent:
          NetworkVlan:
              Id: 1113235
    large:
      cloud_properties:
        Bosh_ip: 10.155.248.130
        Domain: softlayer.com
        VmNamePrefix: bosh-furnace
        EphemeralDiskSize: 20
        StartCpus: 4
        MaxMemory: 8192
        NetworkComponents:
        - MaxSpeed: 1000
        Datacenter:
          Name: dal09
        HourlyBillingFlag: true
        # PrivateNetworkOnlyFlag: true
        PrimaryBackendNetworkComponent:
          NetworkVlan:
              Id: 1113235

networks:
- name: cf1
  type: manual
  subnets:
  - range: 10.155.198.0/26
    gateway: 10.155.198.1
    reserved:
    - 10.155.198.0
    - 10.155.198.1
    - 10.155.198.63
    static:
    - 10.155.198.2-10.155.198.32
    dns: 
    - 10.0.80.11
    - 10.0.80.12
- name: cf1-dynamic
  type: dynamic
  dns: 
  - 10.0.80.11
  - 10.0.80.12
- name: cf2
  type: manual
  subnets:
  - range: 10.155.198.0/26
    gateway: 10.155.198.1
    reserved:
    - 10.155.198.0
    - 10.155.198.1
    - 10.155.198.63
    static:
    - 10.155.198.33-10.155.198.62
    dns: 
    - 10.0.80.11
    - 10.0.80.12
- name: cf2-dynamic
  type: dynamic
  dns: 
  - 10.0.80.11
  - 10.0.80.12

properties:
  ...
```

**Comment by jianqiu** [comment]
@sykesm 
Thanks！We will use the manifest for trial！

**Comment by maximilien** [comment]
As expected with the merge of #127 this one will need to be rebased.

**Comment by maximilien** [comment]
Closing based on @jianqiu #134 and also because we want this to move to `develop_v3`

**Pull request closed without merging**
