### PR TITLE
Baremetal support in bosh-softlayer-cpi

### PR DESCRIPTION
**Pull request by jianqiu**
In order to make softlayer_cpi compatible with baremetal support, we need to make the following changes.

### CODE REVIEW

**Comment by maximilien** [comment]
Not passing Travis. Please update so I review

**Comment by jianqiu** [comment]
@maximilien @mattcui 
I will open another PR to including more changes, so closing it.

**Comment by maximilien** [comment]
@jianqiu do you have the new PR?

**Comment by jianqiu** [comment]
@maximilien 
The new PR is [126](https://github.com/cloudfoundry/bosh-softlayer-cpi/pull/111)

**Pull request closed without merging**
