### PR TITLE
Make build scripts cross-platform

### PR DESCRIPTION
**Pull request by petergtz**
Addresses #148.

### CODE REVIEW

**Comment by maximilien** [comment]
Thanks for this submission @petergtz.

@zhanggbj can you confirm this change will work on your new pipeline. If yes, I will merge.

Thanks both.

Best,

max

**Comment by maximilien** [comment]
Please address conflicts (likely due to PR #195 merge)

**Comment by maximilien** [comment]
Closing this since #194 addresses it. If not then please resubmit. Thx

**Comment by petergtz** [comment]
@maximilien Could this be merged next time instead of cherry-picked? @suhlig and I would have appreciated to get credit for this contribution.

 /cc @smoser-ibm

**Comment by petergtz** [comment]
@zhanggbj Thanks for letting us know. It's okay, such things happen. We just wanted to make sure future contributions will be credited correctly.

Overall, we're happy that our changes are now in there, so we can delete our own fork. Also, we're happy to see that the two repos are now merged.

**Comment by zhanggbj** [comment]
@petergtz Thank you for your understanding!

**Pull request closed without merging**
