### PR TITLE
Change to use getObject to find a stemcell

### PR DESCRIPTION
**Pull request by mattcui**
The major goal of this PR is to fix the problem described in [issue 25](https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/issues/25), the current function of finding a stemcell only can work for private images, to make it also work for public images, I made the change to use getObject SL API to identify a stemcell. In addition, I simplified stemcell find functionality, remove useless functions in [softlayer_finder.go](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/0394806fea641eeab5519dbd85261d53d9c4f818/softlayer/stemcell/softlayer_finder.go), and adjusted unit and integration tests accordingly. The integrate test of [delete_stemcell](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/0394806fea641eeab5519dbd85261d53d9c4f818/integration/delete_stemcell/delete_stemcell_test.go) covered [FindById](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/0394806fea641eeab5519dbd85261d53d9c4f818/softlayer/stemcell/softlayer_finder.go#L27) function. 

@maximilien  It's ready for review and merge. Thanks.

### CODE REVIEW

**Comment by maximilien** [comment]
@mattcui can you do what the @cfdreddbot message mentions above w.r.t. CLA so we stop having this message. Same also for others in Beijing team.

/cc @jianqiu @gu-bin @zhanggbj and @JimmyMa

**Comment by maximilien** [comment]
OK merging. I have limited options here in India to fully test and looks good on perusal. Cheers :+1:

**Comment by sykesm** [comment]
@mattcui I'm still having issues here.

```$ bosh upload stemcell https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/light-bosh-stemcell-3232.6-softlayer-esxi-ubuntu-trusty-go_agent.tgz
Acting as user 'admin' on 'Furnace Bosh'

Using remote stemcell 'https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/light-bosh-stemcell-3232.6-softlayer-esxi-ubuntu-trusty-go_agent.tgz'

Director task 3
  Started update stemcell
  Started update stemcell > Downloading remote stemcell. Done (00:00:00)
  Started update stemcell > Extracting stemcell archive. Done (00:00:00)
  Started update stemcell > Verifying stemcell manifest. Done (00:00:00)
  Started update stemcell > Checking if this stemcell already exists. Done (00:00:00)
  Started update stemcell > Uploading stemcell light-bosh-stemcell-3232.6-softlayer-esxi-ubuntu-trusty-go_agent/3232.6 to the cloud. Failed: Finding stemcell with ID '1152921': Can not find VirtualGuestBlockDeviceTemplateGroup with id `1152921` (00:00:01)

Error 100: Finding stemcell with ID '1152921': Can not find VirtualGuestBlockDeviceTemplateGroup with id `1152921`

Task 3 error

For a more detailed error report, run: bosh task 3 --debug
```

**Comment by jianqiu** [comment]
@sykesm @mattcui @maximilien 
light-bosh-stemcell-3232.6-softlayer-esxi-ubuntu-trusty-go_agent.tgz is still private image template, it still needs sharing your account.
Sorry for the inconvenience caused for your, 
Please try https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/light-bosh-stemcell-3232.8-softlayer-esxi-ubuntu-trusty-go_agent-public.tgz. This is public image template, you could use it directly.
The better way to find the latest public softlayer stemcell is to searching information in our pipeline:
http://159.122.236.143:8080/pipelines/bosh_public_stemcell.

**Comment by mattcui** [comment]
@sykesm Please use the new version (2.3.7) of eCPI, which can support public images. Let us know if there is any problem. Thanks.

https://s3.amazonaws.com/bosh-softlayer-cpi-pipeline/bosh-softlayer-cpi-2.3.7.tgz

**Pull request merged**
